// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzVx2bUCEREUWk_lfuRGPVXQ4-v1XE15Y',
    appId: '1:1079831312834:web:f69f048b21cf327a80fe5b',
    messagingSenderId: '1079831312834',
    projectId: 'portokita-ccb41',
    authDomain: 'portokita-ccb41.firebaseapp.com',
    storageBucket: 'portokita-ccb41.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAanEP4EuTWMza6RvpOOaJDY97czWmej9E',
    appId: '1:1079831312834:android:1279d3c9d43581d180fe5b',
    messagingSenderId: '1079831312834',
    projectId: 'portokita-ccb41',
    storageBucket: 'portokita-ccb41.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnvJ8kS4CGTQY2z2NOXPG8bfrgdnv3D80',
    appId: '1:1079831312834:ios:c07b89a8d16e372480fe5b',
    messagingSenderId: '1079831312834',
    projectId: 'portokita-ccb41',
    storageBucket: 'portokita-ccb41.firebasestorage.app',
    iosBundleId: 'com.example.portokita',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnvJ8kS4CGTQY2z2NOXPG8bfrgdnv3D80',
    appId: '1:1079831312834:ios:c07b89a8d16e372480fe5b',
    messagingSenderId: '1079831312834',
    projectId: 'portokita-ccb41',
    storageBucket: 'portokita-ccb41.firebasestorage.app',
    iosBundleId: 'com.example.portokita',
  );
}
